### ISSUE TITLE
Num_trips doesn't sum up to num_trip_starts

### ISSUE THREAD

**Issue by makmanalp** [araichev/gtfstk#2]
Hi!

I'm trying to use [compute_route_time_series](https://rawgit.com/araichev/gtfstk/master/docs/_build/singlehtml/index.html#gtfstk.calculator.compute_route_time_series) on the [MBTA GTFS files](www.mbta.com/gtfs_archive/archived_feeds.txt) - I'm running a really simple script to calculate trip stats for every hour in the GTFS file, and I'm doing it in batches of days, so I'm running something like this:

```python
import gtfstk
import sys
import pandas as pd

feed = gtfstk.read_gtfs(sys.argv[1], dist_units="mi")
start_date = sys.argv[2]
end_date = sys.argv[3]
print(feed, start_date, end_date)

trip_stats = gtfstk.compute_trip_stats(feed)

dates = [d.strftime('%Y%m%d') for d in pd.date_range(start_date, end_date)]
dfs = []
for d in dates:
    print(d)
    dfs.append(gtfstk.compute_route_time_series(feed, trip_stats, d, freq="1h"))

df = pd.concat(dfs)

```

Then, when I look at num_trips vs num_trip_starts, I see weird patterns. I would expect num_trips to be a version of num_trip_starts where they are piece-wise distributed among the bins depending on how much of the duration of the trip falls within the bin, which means when you sum it it should add up to the same value, right? Here is each value I have for each route, and the values are clearly related but have a very large discrepancy. Any idea why?

<img width="401" alt="screen shot 2017-03-27 at 12 08 23 am" src="https://cloud.githubusercontent.com/assets/161965/24340642/c3997664-1281-11e7-9e62-d54f77ddd2a8.png">

**Comment by araichev** [comment]
Hi makmanalp, 

When GTFSTK computes a route time series, both ``num_trip_starts`` and ``num_trips`` are computed at minute frequency, then downsampled to the desired frequency, e.g. hour-frequency, *but* the kind of downsampling differs for the two quantities.
The ``num_trip_starts`` for the hour is the *sum* of the (integer) ``num_trip_starts`` for each minute, but the ``num_trips`` for the hour is the *mean* of the (integer) ``num_trips`` for each minute.
Downsampling by the mean makes sense in the latter case, because ``num_trips`` represents the number of trips in service during the hour and not all trips that start in the hour run the entire hour.
Taking the mean will weight the trip counts by the fraction of the hour for which the trips are in service.
For example, if two trips start in the hour, one runs for the entire hour, and the other runs for half the hour, then ``num_trip_starts`` will be 2 and ``num_trips`` will be 1.5 for that hour.

I don't know what sum you are referring to in your question, but does my answer clear your confusion?

Maybe i should elaborate the docs on this point.

**Comment by araichev** [comment]
I will elaborate this point in the docs in the next version.
